task/urls.py
from django.urls import path

from .views import (
    index,
    TagListView,
    TagDetailView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDone,

)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path('task-done/<int:pk>/', TaskDone.as_view(), name='task-done'),
    path('task-not-done/<int:pk>/', TaskDone.as_view(), name='task-not-done'),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path("drivers/", TagListView.as_view(), name="driver-list"),
    path(
        "drivers/<int:pk>/", TagDetailView.as_view(), name="driver-detail"
    ),
    path("drivers/create/", TagCreateView.as_view(), name="driver-create"),
    path(
        "drivers/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="driver-update"
    ),
    path(
        "tag/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="driver-delete"
    ),
]

app_name = "task"

task_service/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from task.views import TaskDone

urlpatterns = [
    path("", include("task.urls", namespace="task")),
    path('task_not_done/<int:pk>/', TaskDone.as_view(), name='task-not-done'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/models.py
from django.db import models
from datetime import datetime, timedelta
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)


    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(default=timezone.now)
    deadline = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(default=timezone.now)
    task_is_done = models.BooleanField(default=False)
    tags = models.ForeignKey(Tag, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if not self.datetime:
            self.datetime = timezone.now()
        self.deadline = self.deadline or timezone.now() + timedelta(days=1)
        self.published_date = self.published_date or timezone.now() + timedelta(days=2)
        super(Task, self).save(*args, **kwargs)
    def get_tag_name(self):
        return self.tags.name

    class Meta:
        ordering = ("content", )

    def __str__(self):
        return self.content

task/forms.py
from django.contrib.auth import get_user_model
from django import forms


from task.models import Task, Tag

class TaskLicenseUpdateForm(forms.ModelForm):
    permissions = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

task/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django import forms

import task
from .models import Task, Tag

def index(request):
    """View function for the home page of the site."""

    num_drivers = Task.objects.count()
    tasks_list = Task.objects.all()
    tag_list = Tag.objects.values_list('name', flat=True)
    task_list = Task.objects.values_list('content', 'datetime', 'published_date', 'tags')
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "tasks_list": tasks_list,
        "num_drivers": num_drivers,
        "tag_list": tag_list,
        "task_list": task_list,
        "num_visits": num_visits + 1,
    }

    return render(request, "task/index.html", context=context)


class TaskListView(generic.ListView):
    model = Task
    fields = "__all__"
    paginate_by = 5
    template_name = "task/index.html"

class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = ["tags"]
    success_url = reverse_lazy("task:task-list")
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = self.get_object()
        context['tag_id'] = task.tags.id
        return context


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task:task-list")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5
    template_name = "task/task_list.html"


class TagDetailView(generic.DetailView):
    model = Tag
    queryset = Tag.objects.all().prefetch_related("cars__manufacturer")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:driver-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:driver-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:driver-list")

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_is_done']


class TaskDone(generic.UpdateView):
    model = Task
    fields = ["task_is_done"]

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.task_is_done = not self.object.task_is_done
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy("task:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Task Service</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <br>
  <h4><li class="list-group-item"><a href="{% url 'task:task-list' %}">Home</a></li></h4>
  <h4><li class="list-group-item"><a href="{% url 'task:driver-list' %}">Tags</a></li></h4>
</ul>

templates/task/index.html
{% extends "base.html" %}

{% block content %}
  <h1>TODO list <a href="{% url 'task:task-create' %}" class="btn text-light btn-primary link-to-page">Add task</a></h1>
  {% if task_list %}
  <table class="table">
  {% for task in task_list %}
   {% if task.task_is_done %}
    <h4>{{ task.content }} Done <a href="{% url 'task:task-done' pk=task.pk %}" class="btn text-light btn-secondary link-to-page1">Undo</a></h4>
   {% else %}
    <h4>{{ task.content }} Note done <a href="{% url 'task-not-done' pk=task.pk %}" class="btn text-light btn-success link-to-page2">Complete</a></h4>
   {% endif %}
   <p>Created: {{ task.published_date|date:"F j, Y, g:i a" }} Deadline: {{ task.deadline }}</p>
       <a>
         <h4>
             Tags: {{ task.tags }}
             <div class="btn-group">
                <h4>{{tag_list}}</h4>
                 <h4><a href="{% url 'task:task-update' pk=task.pk %}">Update</a></h4>
                 <h4><a href="{% url 'task:task-delete' pk=task.pk %}">Delete</a></h4>
             </div>
         </h4>
       </a>
   </tr>
  {% endfor %}
  </table>
  {% else %}
    <p>There are no drivers in the service.</p>
  {% endif %}
{% endblock %}

templates/task/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/task_done.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
        Tags<a href="{% url "task:driver-create" %}" class="btn text-light btn-primary link-to-page">Add</a>
    </h1>

    {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for tag_name in tag_list %}
      <tr>
        <td class="text-dark">
          <h4>{{tag_name}}</h4>
        </td>
        <td>
          <h4><a href="{% url 'task:driver-update' pk=tag_name.id %}" class="btn text-light btn-secondary">Update</a></h4>
        </td>
        <td>
          <h4><a href="{% url 'task:driver-delete' pk=tag_name.id %}" class="btn text-light btn-secondary">Delete</a></h4>
        </td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no drivers in the service.</p>
    {% endif %}
{% endblock %}